### PR TITLE
Fix output and parallelize building process (#8)

### PR DESCRIPTION
**Pull request by proletarius101**
Fixed by adding an alias.

### CODE REVIEW

**Comment by proletarius101** [comment]
Ah, sorry I did't target dev. If you want I will raise another one.

**Comment by proletarius101** [comment]
So I managed to let it run. However, there is still a strange issue:
````
05-14 23:25:55.122 18444 18444 I Clash   : Clash starting
05-14 23:25:55.150 18444 18444 W Clash   : Package com.android.bluetooth not found
05-14 23:25:55.150 18444 18444 W Clash   : java.lang.NullPointerException: throw with null exception
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute$Companion$packageManager$2.invoke(ExecAttribute.kt:28)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute$Companion$packageManager$2.invoke(ExecAttribute.kt:17)
05-14 23:25:55.150 18444 18444 W Clash   : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute$Companion.getPackageManager(Unknown Source:11)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute$Companion.access$getPackageManager$p(ExecAttribute.kt:17)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute.loadPackageUid(ExecAttribute.kt:97)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute.parseBlacklistUid(ExecAttribute.kt:84)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute.access$parseBlacklistUid(ExecAttribute.kt:11)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute$blacklistUid$2.invoke(ExecAttribute.kt:42)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute$blacklistUid$2.invoke(ExecAttribute.kt:11)
05-14 23:25:55.150 18444 18444 W Clash   : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute.getBlacklistUid(Unknown Source:7)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute.buildEnvironment(ExecAttribute.kt:49)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute.access$buildEnvironment(ExecAttribute.kt:11)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute$environment$2.invoke(ExecAttribute.kt:36)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute$environment$2.invoke(ExecAttribute.kt:11)
05-14 23:25:55.150 18444 18444 W Clash   : 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute.getEnvironment(Unknown Source:7)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecSetup.exec(ExecSetup.kt:28)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecSetup.started(ExecSetup.kt:19)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecProcess.<init>(ExecProcess.kt:48)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.ExecAttribute.start(ExecAttribute.kt:39)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.Starter.exec(Starter.kt:38)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.github.kr328.clash.Main.main(Main.kt:19)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-14 23:25:55.150 18444 18444 W Clash   : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
05-14 23:25:55.505 18444 18444 I Clash   : Clash started
05-14 23:25:55.505 18444 18486 V Clash   : execv: Permission denied
05-14 23:25:55.505 18444 18486 I Clash   : Clash process exited
05-14 23:25:55.591 18444 18444 I Clash   : Clash stopped
````

So it's bascially https://github.com/Kr328/ClashForMagisk/blob/586873a5282a9089fcc29df1bc938302725493c6/starter/src/main/java/com/github/kr328/clash/model/Initial.kt#L11

**Comment by proletarius101** [comment]
I'm surprised... A while loop to act like a service is way too expensive...
https://github.com/Kr328/ClashForMagisk/blob/586873a5282a9089fcc29df1bc938302725493c6/starter/src/main/java/com/github/kr328/clash/Starter.kt#L24

**Comment by Kr328** [comment]
It is a basic `event-driven model`. loop will **block** in `eventQueue.poll` to wait event, it not a lot of overhead

**Comment by proletarius101** [comment]
OK, I see. Then there must be other problem accounting for 100% cpu usage.

**Pull request closed without merging**
